[versions]
activityKtx = "1.8.2"
kotlinxCoroutinesCore = "1.7.3"
project = "1.0.0"
iosDeploymentTarget = "14.1"
agp = "8.2.2"
android-minSdk = "29"
android-compileSdk = "34"
kotlin = "1.9.22"
androidx-core-ktx = "1.12.0"
compose = "1.6.0"
compose-plugin = "1.5.12"
appcompat = "1.6.1"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }